### ISSUE TITLE
Disconnect：Transport connection was closed due to the requested video format not being available

### ISSUE THREAD

**Issue by Bornblack** [microsoft/MixedReality-HolographicRemoting-Samples#10]
Actually It's not the application in this hub produces this error. When I try to connect Unity (2019.4.1f1) with Holographic Remoting Player (V2.2.2.0）in Mircosoft Store, It comes up with **Disconnect：Transport connection was closed due to the requested video format not being available** in Hololens . As for unity , the error is below:
                     **Disconnected with error 22  
                     UnityEditor.EditorApplication:Internal_CallUpdateFunctions()**     
 Any idea to fix that ?  Thanks！

**Comment by svandex** [comment]
I am using UE4.25.3, I have the same problem. I package the app once, and it broken my ue4 editor. After I open it again, I cannot use holographic remoting as this error appears.

**Comment by Bornblack** [comment]
Probably you should upgrade your graphic card. The holographic remoting rendering relies on the H265 hardware video decoding ,which means your GPU should support that. Check:
**https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements**
I have upgraded my graphic card and the issue is gone for me!

**Comment by svandex** [comment]
@Bornblack I am using K2200 which support h.265

**Comment by FlorianBagarMicrosoft** [comment]
Disconnect reason "Transport connection was closed due to the requested video format not being available" indicates that you most likely do not have installed the HEVC codec either on the PC or on the HoloLens. One way to fix this is to install the HEVC Video Extensions from the Microsoft Store (see https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7?activetab=pivot:overviewtab).
