### ISSUE TITLE
Error while building player sample

### ISSUE THREAD

**Issue by michalt38** [microsoft/MixedReality-HolographicRemoting-Samples#28]
I'm encountering the following error while building the player sample project:
`OperationFailedException: Error HRESULT E_FAIL has been returned from a call to a COM component.`
Could you please help fixing this?

**Comment by maapp** [comment]
Hi,

a couple questions - which version are you building? Head?
And second: Does this error occur during building or when you try to run what you built?

**Comment by michalt38** [comment]
Yes, I'm building head and this happens when I try to run it. The whole compilation is fine.

**Comment by maapp** [comment]
So, I just spoke to a colleague and he told me that he's seen this problem before and it seems to be a Visual Studio issue.
A workaround is to install the appx manually instead of letting Visual Studio deploy it.
Cleaning the workspace via git clean -xdf sometimes also helps.

If you can run it after deploying it manually I'd ask you to report this with the Visual Studio team - maybe they can help you.

**Comment by maapp** [comment]
Closing this issue now, I hope that your problems have been solved. If not let us know.
