### ISSUE TITLE
About OverRenderingConfig

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedReality-HolographicRemoting-Samples#39]
The newest sample used the OverRenderingConfig. What does the 10% over render mean? What is the benefit of adding this?

**Comment by FlorianBagarMicrosoft** [comment]
For unpredictable motion the predicted viewport on the remote side and the actual viewport on the player side can differ, say the remote frame does not fully align with the display at the time the remote frame is rendered on the HoloLens. Due to that the sides of the frustum are cut, which can be visible as black regions at the sides on the HMD. The OverRenderingConfig specifies a percentage size increase to the actual viewport, so that the predicted viewport becomes larger and therefore less cutting occurs. With an increased viewport size the pixel density decreases therefore, the OverRenderingConfig allows to increase the resolution as well. If the viewport increase is equal to the resolution increase the pixel density remains the same.

**Comment by qian256** [comment]
Thanks @FlorianBagarMicrosoft ! That's helpful
