### ISSUE TITLE
C# sample

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedReality-HolographicRemoting-Samples#40]
I wonder if there is plan for enabling a C# player/remote sample?

**Comment by maapp** [comment]
Hi @qian256 - we currently have no plans for a dedicated C# sample for remoting.

My suggestion would be that you build a small native DLL which wraps the remoting portion, shares the render textures via shared handles with your C# renderer and thus limits the surface you need to interact with.

**Comment by zaalsabb** [comment]
@maapp 

Hi, would this suggestion work for the player if I want to run it as part of a unity app?

Thanks,
Zaid

**Comment by maapp** [comment]
Hi @zaalsabb - can you elaborate a bit on your use case? In general with Holographic Remoting you have the player running on the target device and then stream the content from the app producing the frames to that player. The player takes over control of the display output etc. of the target device so Unity wouldn't be involved on the HoloLens for example.

**Comment by zaalsabb** [comment]
Hi @maapp, 

My use case more specifically is that I'm using Holographic remoting to view large scale point cloud data on the HL2, as well as perform other functions. My only issue so far is that I can't use the camera on-board the HL2 while using holographic remoting, since whenever my app tries to access the camera it can only use the PC's webcam. 

The workaround that I am thinking of implementing is to customize the player application so that it can capture images from the HL2 device and then send them to my app running on the PC using a standard post request. Maybe I can add something like this to [this](https://github.com/Microsoft/Windows-universal-samples/tree/main/Samples/HolographicFaceTracking) to the custom player app to capture the images from the HL2. Do you think this is feasible? Or are there better ways to go about this?

Thanks!
Zaid

**Comment by maapp** [comment]
Hi @zaalsabb,
Customizing the player application is definitely the way to go - we also have a feature we call "custom data channels" which you can use to transmit your data over the existing remoting connection easily. Documentation for that is here: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/holographic-remoting-custom-data-channels

We have other customers using this to do more expensive AI processing for example on the PC side so I think this fits your use case quite well.
