### ISSUE TITLE
SampleHolographicRemotingPlayer 2.9.0 cannot be opened

### ISSUE THREAD

**Issue by SuperG-2020** [microsoft/MixedReality-HolographicRemoting-Samples#85]
**Describe the bug**
SampleHolographicRemotingPlayer 2.9.0 sometimes fails to open,When WIFI is turned off, it can be turned on. It can be opened normally with Holographic Remoting Player.

**To Reproduce**
1. The software cannot be opened
https://user-images.githubusercontent.com/73644992/224667004-40464427-2e12-450b-a786-42e49c3d13bc.mp4
2. Can be turned on after turning off wifi
https://user-images.githubusercontent.com/73644992/224667261-47b54207-77f6-452f-8612-a790544e6b67.mp4
3. Holographic Remoting Player can be opened normally
https://user-images.githubusercontent.com/73644992/224667461-42d2b8cd-e243-4234-bcd8-a14376b97c36.mp4

**Remote side (your Windows PC):**
1. Visual Studio 2022
2. Windows 10 SDK (10.0.22621.0)
3. MSVC v143
4. Microsoft.Holographic.Remoting 2.9.1
5. Microsoft.Windows.CppWinRT 2.0.230225.1

**Comment by SuperG-2020** [comment]
There is no crash during debugging and it can be opened normally. It is strange that there are some exceptions in the output log. I don't know if this is related
[Log output during debugging.txt](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/files/10964031/Log.output.during.debugging.txt)

**Comment by ikto-art** [comment]
Hi,

I have the same problem with a player built using the last 2.8.1 commit (#64) however it doesn't seem to be linked to Wi-Fi problems, since other HoloLenses with the same application within the same range and Wi-Fi continue to work.
It seems I have to uninstall the app and install it again for it to work (sometimes more than once).
I tried with and without Kiosk mode.

Do you have any guidance on how to gather logs or traces?
Thanks.

**Comment by simonrobl** [comment]
@SuperG-2020, @ikto-art closing this ticket since it hasn't been active in some time. Are you still running into this issue on your end? Does the problem persist when using the latest version of the player? If so feel free to reopen this issue :)
